#!/bin/sh

# Pull the repo
WORKDIR=$(realpath .)
mkdir /tmp/alt4temp
cd /tmp/alt4temp || return

# TODO: Change to use tags instead
wget https://github.com/alt4dev/protobuff/archive/refs/heads/master.zip
unzip master.zip
cd protobuff-master || return

./build.sh python "$WORKDIR/alt4/proto"

rm -r /tmp/alt4temp

git add alt4/proto

echo "Commit the changes if any."